name: My First GitHub Actions

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest


    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py

    - name: Debug Secrets
      run: |
        echo "ACCESS_KEY: ${{ secrets.ACCESS_KEY }}"
        echo "SECRET_KEY: ${{ secrets.SECRET_KEY }}"
        echo "BUCKET: ${{ secrets.BUCKET }}"

    - uses: shallwefootball/s3-upload-action@master
      name: Upload to S3 bucket
      id: S3
      with:
        aws_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_KEY}}
        aws_bucket: ${{ secrets.BUCKET }}
        source_dir: src
